version: '3'
services: # all the container that we want to run
  webhost: # name of the container
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app